import type { Metadata } from "next";
import { Geist, Geist_Mono, Pacifico, Meow_Script } from "next/font/google";
import "./globals.css";
// import { ThemeProvider } from "@/components/theme-provider";

const meowScript = Meow_Script({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-meow",
  display: "swap",
});

const pacifico = Pacifico({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-pacifico",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "For Shrav.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${meowScript.variable} ${pacifico.variable} antialiased`}
      >
        {/* <ThemeProvider> */}

        {children}
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
